# ============================================
# Practo Automation - Configuration File
# ============================================

# Base URL
base.url=https://www.practo.com

# Browser: chrome, edge, or firefox
browser=chrome

# Waits (in seconds)
implicit.wait=10
explicit.wait=15
page.load.timeout=30

# Screenshot folder
screenshot.path=screenshots/

# Report folder
report.path=reports/

# ===== Driver Paths (Local Only - CI uses WebDriverManager) =====
chrome.driver.path=C:\\Users\\2485864\\eclipse-workspace\\April2026SeleniumTraining\\drivers\\chromedriver.exe
edge.driver.path=C:\\Users\\2485864\\Downloads\\edgedriver_win64\\msedgedriver.exe
firefox.driver.path=C:\\Users\\2485864\\Downloads\\geckodriver-win64\\geckodriver.exe